version: '3'

services:
  db:
    image: postgres:15.3-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pgpassword

  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always

volumes:
  db_data: {}