# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/warehouse_items', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # WarehouseItem. As you add validations to WarehouseItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      warehouse_order_id: create(:warehouse_order).id,
      item_id: create(:item).id,
      quantity: Faker::Number.number(digits: 2),
      total_requested_quantity: Faker::Number.number(digits: 2),
      total_confirmed_quantity: Faker::Number.number(digits: 2),
      picked_up_quantity: Faker::Number.number(digits: 2)
    }
  end

  let(:invalid_attributes) do
    {
      warehouse_order_id: nil,
      item_id: nil,
      quantity: Faker::Number.number(digits: 2),
      total_requested_quantity: Faker::Number.number(digits: 2),
      total_confirmed_quantity: Faker::Number.number(digits: 2),
      picked_up_quantity: Faker::Number.number(digits: 2)
    }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # WarehouseItemsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {}
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      WarehouseItem.create! valid_attributes
      get warehouse_items_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      warehouse_item = WarehouseItem.create! valid_attributes
      get warehouse_item_url(warehouse_item), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new WarehouseItem' do
        expect do
          post warehouse_items_url,
               params: { warehouse_item: valid_attributes }, headers: valid_headers, as: :json
        end.to change(WarehouseItem, :count).by(1)
      end

      it 'renders a JSON response with the new warehouse_item' do
        post warehouse_items_url,
             params: { warehouse_item: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new WarehouseItem' do
        expect do
          post warehouse_items_url,
               params: { warehouse_item: invalid_attributes }, as: :json
        end.to change(WarehouseItem, :count).by(0)
      end

      it 'renders a JSON response with errors for the new warehouse_item' do
        post warehouse_items_url,
             params: { warehouse_item: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          quantity: Faker::Number.number(digits: 2)
        }
      end

      it 'updates the requested warehouse_item' do
        warehouse_item = WarehouseItem.create! valid_attributes
        patch warehouse_item_url(warehouse_item),
              params: { warehouse_item: new_attributes }, headers: valid_headers, as: :json
        warehouse_item.reload
        expect(warehouse_item.quantity).to eq new_attributes[:quantity]
      end

      it 'renders a JSON response with the warehouse_item' do
        warehouse_item = WarehouseItem.create! valid_attributes
        patch warehouse_item_url(warehouse_item),
              params: { warehouse_item: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the warehouse_item' do
        warehouse_item = WarehouseItem.create! valid_attributes
        patch warehouse_item_url(warehouse_item),
              params: { warehouse_item: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested warehouse_item' do
      warehouse_item = WarehouseItem.create! valid_attributes
      expect do
        delete warehouse_item_url(warehouse_item), headers: valid_headers, as: :json
      end.to change(WarehouseItem, :count).by(-1)
    end
  end
end
