default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: pgpassword
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: postgres://render_db_wau6_user:arKzuxmtZRaGinl6LossR9K4qrL8E64g@dpg-cir3vdlph6ev5r9uh630-a.oregon-postgres.render.com/render_db_wau6
  database: pod_dev

test:
  <<: *default
  database: pod_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
