name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Ruby and Bundler
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      # Add or replace dependency steps here
      - name: Install gems
        run: bundle install

      # Add or replace database setup steps here
      - name: Set file permissions
        run: chmod +x bin/rails
      - name: Set up database schema
        run: bin/rails db:schema:load

      # Add or replace test runners here
      - name: Run RSpec tests
        run: bundle exec rspec
